# Generated by Django 3.2.7 on 2021-12-22 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_sizeable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('height', models.CharField(blank=True, max_length=3, null=True)),
                ('neck', models.CharField(blank=True, max_length=3, null=True)),
                ('shoulder', models.CharField(blank=True, max_length=3, null=True)),
                ('chest', models.CharField(blank=True, max_length=3, null=True)),
                ('arm', models.CharField(blank=True, max_length=3, null=True)),
                ('back', models.CharField(blank=True, max_length=3, null=True)),
                ('waist', models.CharField(blank=True, max_length=3, null=True)),
                ('hips', models.CharField(blank=True, max_length=3, null=True)),
                ('leg', models.CharField(blank=True, max_length=3, null=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
