# Generated by Django 3.2.7 on 2021-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('made_to_measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtmorder',
            name='garment',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
