# Generated by Django 3.2.7 on 2021-12-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sizeable'),
        ('made_to_measure', '0002_mtmorder_garment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtmorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
