# Generated by Django 3.2.7 on 2021-12-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('made_to_measure', '0003_alter_mtmorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtmorder',
            name='arm',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='back',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='chest',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='height',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='hips',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='leg',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='neck',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='shoulder',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mtmorder',
            name='waist',
            field=models.CharField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
