# Generated by Django 3.2.7 on 2022-01-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_mtmprofile'),
        ('made_to_measure', '0006_mtmorder_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtmorder',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mtm_orders', to='profiles.userprofile'),
        ),
    ]
