# Generated by Django 3.2.7 on 2022-01-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('made_to_measure', '0007_alter_mtmorder_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtmorder',
            name='user_profile',
        ),
    ]
