# Generated by Django 3.2.7 on 2022-01-08 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_userprofile_default_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_email', models.CharField(blank=True, max_length=254, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_height', models.CharField(blank=True, max_length=3, null=True)),
                ('default_neck', models.CharField(blank=True, max_length=3, null=True)),
                ('default_shoulder', models.CharField(blank=True, max_length=3, null=True)),
                ('default_chest', models.CharField(blank=True, max_length=3, null=True)),
                ('default_arm', models.CharField(blank=True, max_length=3, null=True)),
                ('default_back', models.CharField(blank=True, max_length=3, null=True)),
                ('default_waist', models.CharField(blank=True, max_length=3, null=True)),
                ('default_hips', models.CharField(blank=True, max_length=3, null=True)),
                ('default_leg', models.CharField(blank=True, max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
