# Generated by Django 3.2.7 on 2021-12-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizeable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
